# Generated by Django 4.2.16 on 2024-10-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please Enter Book Title', max_length=300, verbose_name='Title')),
                ('summary', models.TextField(help_text='Please Enter Book Description', max_length=1500, verbose_name='Description')),
                ('isbn', models.IntegerField(help_text='13 Characters <a href="https://isbnsearch.org/">ISBN Search </a>', max_length=13, unique=True, verbose_name='ISBN-13')),
                ('genre', models.ManyToManyField(help_text='Select one or many Genre for the Book.', to='lms_app.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('uniqueid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Book Copy in Library', primary_key=True, serialize=False, verbose_name='UUID')),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On Loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book Availability', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lms_app.book')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_back', 'imprint'],
            },
        ),
    ]
