# Generated by Django 4.2.16 on 2024-10-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_bookcopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Characters <a href="https://isbnsearch.org/">ISBN Search </a>', max_length=13, unique=True, verbose_name='ISBN-13'),
        ),
    ]
