# Generated by Django 4.2.16 on 2024-11-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_author_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'ordering': ['due_back', 'imprint'], 'permissions': (('can_mark_returned', 'Set Book As Returned'),)},
        ),
    ]
