# Generated by Django 4.2.16 on 2024-11-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_alter_bookcopy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name'], 'permissions': [('create_author', 'Create and Update Author')]},
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text="Please Enter Author's Last Name", max_length=200),
        ),
    ]
