# Generated by Django 4.2.16 on 2024-11-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_alter_author_options_alter_author_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name'], 'permissions': [('update_author', 'Update Author'), ('create_author', 'Create Author')]},
        ),
    ]
